### ISSUE TITLE
Clearing Error Stack to Remove Notices on error reporting

### ISSUE THREAD

**Issue by davidsalazar** [geerlingguy/Imap#13]
How come you don't call imap_errors() on your thrown exception instead of imap_last_error()? 

I had an issue with notices being thrown because that doesn't clear the error stack like imap_errors() does.   I hope i didn't miss something, what do you think?

**Comment by geerlingguy** [comment]
To be honest, I haven't thought about that at all, since I was cleaning up and improving Kastang's code, and was mostly focused on getting things working well. If I can get around to testing imap_errors(), and it seems to work well, I might replace it.

I'm also happy to look at pull requests :)
