### ISSUE TITLE
Attachment Support

### ISSUE THREAD

**Issue by chrisgillis** [geerlingguy/Imap#16]
Attachment support would make this a pretty killer class.

**Comment by geerlingguy** [comment]
Agreed... while I haven't had need to do attachments in any of the projects for which I'm using Imap, I can see the utility. I'd like to keep it clean and simple.

**Comment by yuvrajingale** [comment]
I am trying to fetch the attachment from Message body using "Multipart" getBodyType() . but i am not able to fetch the attachment can you please help me for this or just guide how to proceed .

**Comment by geerlingguy** [comment]
I'm going to try to wrap [`imap_fetchstructure()`](http://www.php.net/manual/en/function.imap-fetchstructure.php) with something like a `getAttachments()` method... helpful post: [Extracting attachments from an email message using PHP IMAP functions](http://www.electrictoolbox.com/extract-attachments-email-php-imap/).
