### ISSUE TITLE
Detect Auto-Responders (Out of Office)

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/Imap#6]
One of the most annoying things in the world is a system that pulls in the myriad of annoying and silly autoresponses from (almost always) Outlook. IMO, people should just forget about adding out of office replies, and others should simply presume that the person they emailed is either away or dead if they don't get a response within a few days.

Anyways, as it is, I have to deal with autoresponders, and they should, presumably, send back an 'Auto-Submitted' header in the email (see [this answer on Stack Exchange](http://stackoverflow.com/a/7070621/100134)). However, I've never gone deep into this area, so I need to do some research and see how the out of office replies work from different clients.

Here are some interesting tidbits I found when looking up various solutions to the autoresponder/vacation/away/out-of-office problem:
- One of the methods for detection used by Exim: http://wiki.exim.org/EximAutoReply#Example_2 — they seem to simply run a message's headers through a bunch of searches, and if any keywords are found, they mark the message accordingly.
- (MailChimp built ReplyTo)[http://blog.mailchimp.com/introducing-replyto-omg-make-the-auto-replies-go-away/] to help people handle responses, but it's in private beta (as of this writing).
- Microsoft has proposed an `X-Auto-Response-Suppress` header to indicate to mail servers whether the email should be responded to. See (X-Auto-Response-Suppress documentation)[http://msdn.microsoft.com/en-us/library/ee219609(v=exchg.80).aspx]. (Exchange, btw, also only sends one out-of-office reply per email sender... so that's a nice non-proliferation tool, at least).
- CampaignMonitor has a (blog post)[http://www.campaignmonitor.com/blog/post/3677/handling-email-campaign-bounce-backs-and-autoreplies] with guidelines for handling bounces and out-of-office replies (more for end-users).
- Joss Crowcroft heralds the (death of the no-reply box)[http://www.josscrowcroft.com/2011/random/death-to-the-noreply-mailbox/](and makes some good points!).

**Comment by geerlingguy** [comment]
Right now I'm logging a ton of different responses (some from real people, some from autoresponders), and I'm trying to find some patterns. I'll jot down some notes in this comment.
- `X-Autorespond` header in response - 1 time
- `Auto Response` in subject line (from yahoo.com) - 1 time

**Comment by geerlingguy** [comment]
Above commit adds a few more strings to search in the headers. I'll leave this issue open as I roll out this detection and log everything in a few different places, so I can add to the filter as needed.

**Comment by geerlingguy** [comment]
I'm opening up separate issues for dealing with different email providers' OOO messages.

**Comment by ava-adamb** [comment]
Did you end up opening another issue?

**Comment by geerlingguy** [comment]
I think I just did it through a few separate commits. I haven't had a particular need for any further support than what's currently in the library since I'm not working on the project that was the original motivation behind this library anymore.
